name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: 1.19.x
            otp: 28.x
            check_formatted: true
          - elixir: 1.18.x
            otp: 27.x
          - elixir: 1.17.x
            otp: 27.x
          - elixir: 1.16.x
            otp: 26.x
          - elixir: 1.15.x
            otp: 25.x
          - elixir: 1.14.x
            otp: 25.x

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        id: setup-elixir
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.setup-elixir.outputs.otp-version }}-${{ steps.setup-elixir.outputs.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted
        if: matrix.check_formatted

      - name: Run tests
        run: mix test
